#!/bin/bash -l

#SBATCH --account=s658
#SBATCH --job-name="test_static"
#SBATCH --output=test_static_out_%j.txt
#SBATCH --error=test_static_err_%j.txt
#SBATCH --time=00:30:00
#SBATCH --nodes=4
#SBATCH --partition=debug
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --threads-per-core=2
#SBATCH --constraint=gpu
export CRAY_CUDA_MPS=1


export LD_LIBRARY_PATH=/users/novatig/accfft/build_cuda/:/apps/daint/UES/jenkins/6.0.UP02/gpu/easybuild/software/GSL/2.1-CrayGNU-2016.11/lib:/opt/cray/job/2.0.2_g98a4850-2.43/lib64:/opt/gcc/5.3.0/snos/lib64:/apps/common/UES/SLES12/ddt/7.0/lib/64:/apps/common/UES/SLES12/ddt/7.0/lib
module load daint-gpu GSL/2.1-CrayGNU-2016.11 cray-hdf5-parallel/1.10.0
module load cudatoolkit/8.0.44_GA_2.2.7_g4a6c213-2.1 fftw/3.3.4.10
export OMP_NUM_THREADS=24
export MYROUNDS=10000
export USEMAXTHREADS=1
srun --ntasks 4 --threads-per-core=2 --ntasks-per-node=1 --cpus-per-task=12 ../ms
#./simulation 
