#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=8
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1:00:00
#SBATCH --partition=viz
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cconti@mavt.ethz.ch

#SBATCH --job-name=HDF2CH
#SBATCH --account=s436

export OMP_NUM_THREADS=8

export SCR=/scratch/daint/cconti/FallingSamaraFixed_24h_1024_310116
mkdir -p $SCR

cp HDF2ch_Daint.sh $SCR/.
cp submit_daint $SCR/.
cp hdf2ch $SCR/.
cp ../ch2hdf/ch2hdf $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

BPDYZ=64

aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./hdf2ch -xpesize 2 -ypesize 2 -zpesize 2 -bpdx 16 -bpdy 16 -bpdz 16 -sim io -simdata FallingSamaraFixed_24h_1024_310116-000000.h5 -outdata chi -channel 4 -stepid 0
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./ch2hdf -simdata chi00000.StreamerGridPointIterative.channel0 -h5file outChi
