#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=2:00:00
#SBATCH --partition=viz
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cconti@mavt.ethz.ch

#SBATCH --job-name=HDF2CH
#SBATCH --account=s436

export OMP_NUM_THREADS=8

NAME=FallingSamaraFixed_long_DP_512_180216_Dora
export SCR=/scratch/daint/cconti/${NAME}
mkdir -p $SCR

cp HDF2ch_Daint.sh $SCR/.
cp submit_daint_specific $SCR/.
cp hdf2ch $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

CHI_OUT="chi"
VORT_OUT="vorticity"

aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./hdf2ch -xpesize 4 -ypesize 4 -zpesize 4 -bpdx 4 -bpdy 4 -bpdz 4 -sim io -simdata ${NAME}-698704.h5 -stepid 698704 -threshold 1e-10 -channel 6 -outdata ${VORT_OUT}
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./hdf2ch -xpesize 4 -ypesize 4 -zpesize 4 -bpdx 4 -bpdy 4 -bpdz 4 -sim io -simdata ${NAME}-698704.h5 -stepid 698704 -threshold 1e-10 -channel 4 -outdata ${CHI_OUT}
