#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=6:00:00
#SBATCH --partition=viz
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cconti@mavt.ethz.ch

#SBATCH --job-name=HDF2CH
#SBATCH --account=s436
#SBATCH --partition=viz

export OMP_NUM_THREADS=8

NAME=CVT_Re10k_M.1
export SCR=/scratch/daint/cconti/CVT/${NAME}
mkdir -p $SCR

cp HDF2ch_Daint.sh $SCR/.
cp submit_daint_cvt $SCR/.
cp hdf2ch $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

VORT_OUT="vorticity"

for F in $(ls *.h5)
do
   S=$(awk 'BEGIN {FS="[g|.]"} {print $2}' <<< $F)
   if [ ! -f ${VORT_OUT}${S}.StreamerGridPointIterative.channel0 ];
   then
        aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./hdf2ch -xpesize 4 -ypesize 4 -zpesize 4 -bpdx 4 -bpdy 8 -bpdz 6 -sim io -simdata VortMag${S}.h5 -stepid ${S} -threshold 1e-10 -channel 0 -outdata ${VORT_OUT}
   fi
done
