#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=12
#SBATCH --time=12:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cconti@mavt.ethz.ch

#SBATCH --job-name=HDF2CH
#SBATCH --account=s436

export OMP_NUM_THREADS=12

NAME=FallingSamaraFixed_long_DP_512_180216_Dora
export SCR=/scratch/daint/cconti/${NAME}
mkdir -p $SCR

cp HDF2ch_Dora.sh $SCR/.
cp submit_dora $SCR/.
cp hdf2ch $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

CHI_OUT="chi"
VORT_OUT="vorticity"

for F in $(ls *.h5)
do
   S=$(awk 'BEGIN {FS="[-|.]"} {print $2}' <<< $F)
   if [ ! -f ${CHI_OUT}${S}.StreamerGridPointIterative.channel0 ];
   then
        aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 12 ./hdf2ch -xpesize 4 -ypesize 4 -zpesize 4 -bpdx 4 -bpdy 4 -bpdz 4 -sim io -simdata ${NAME}-${S}.h5 -stepid ${S} -threshold 1e-10 -channel 6 -outdata ${VORT_OUT}
   fi
   if [ ! -f ${VORT_OUT}${S}.StreamerGridPointIterative.channel0 ];
   then
        aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 12 ./hdf2ch -xpesize 4 -ypesize 4 -zpesize 4 -bpdx 4 -bpdy 4 -bpdz 4 -sim io -simdata ${NAME}-${S}.h5 -stepid ${S} -threshold 1e-10 -channel 4 -outdata ${CHI_OUT}
   fi
done
