#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=2:00:00
#SBATCH --partition=viz
#SBATCH --mail-type=ALL
#SBATCH --mail-user=cconti@mavt.ethz.ch

#SBATCH --job-name=vpcachier
#SBATCH --account=s436

export OMP_NUM_THREADS=8

NAME=FallingSamaraFixed_24h_1024_310116
export SCR=/scratch/daint/cconti/${NAME}
mkdir -p $SCR

cp vpcachier.sh $SCR/.
cp submit_daint_vpcachier $SCR/.
cp vpcachier $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./vpcachier -wtype_read 1 -wtype_write 3 -eps 0 -min 0 -max 1 -simdata chi62360.StreamerGridPointIterative.channel0 -vp chi62360
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./vpcachier -wtype_read 1 -wtype_write 3 -eps 0 -min 0 -max 1000 -simdata vorticity62360.StreamerGridPointIterative.channel0 -vp vorticity62360




