#!/bin/bash -l

#SBATCH --account=s658
#SBATCH --job-name="FlowPastFixedCylRe050_CFL0.1_testScaling"
#SBATCH --output=FlowPastFixedCylRe050_CFL0.1_testScaling_%j.txt
#SBATCH --error=FlowPastFixedCylRe050_CFL0.1_testScaling_%j.txt
#SBATCH --time=00:30:00
#SBATCH --nodes=1
# #SBATCH --partition=viz
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --constraint=gpu
export CRAY_CUDA_MPS=1


export LD_LIBRARY_PATH=/users/novatig/accfft/build_cuda/:/apps/ela/system/lib
module load daint-gpu GSL/2.1-CrayGNU-2016.11 cray-hdf5-parallel/1.10.0
module load cudatoolkit/8.0.44_GA_2.2.7_g4a6c213-2.1 fftw/3.3.4.10
export OMP_NUM_THREADS=24
export MYROUNDS=10000
export USEMAXTHREADS=1
srun -n 1 --ntasks-per-node=1 --cpus-per-task=24 ./simulation  -bpdx 128 -bpdy 64 -bpdz 16 -2Ddump 1 -nprocsx 1 -CFL 0.1 -uinfx 0.1 -length 0.1 -lambda 1e4 -nu 0.0002 -tend 10 -tdump 1 -nsteps 101
