#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00
#SBATCH --output=Mordant.%j.o
#SBATCH --error=Mordant.%j.e

#SBATCH --job-name=Mordant2_SP_1024_200316
#SBATCH --account=s436
#SBATCH --partition=viz

export SCR=/scratch/daint/cconti/${SLURM_JOB_NAME}
mkdir -p $SCR

cp ../makefiles/simulation_mordant $SCR/.
cp MordantDaint.sh $SCR/.
cp submit_Mordant $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

BPDY=32
BPDZ=32

export OMP_NUM_THREADS=8
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./simulation_mordant -file ${SLURM_JOB_NAME} -sim falling -tend 10. -nprocsx ${SLURM_NTASKS} -nprocsy 1 -nprocsz 1 -bpdx 1 -bpdy ${BPDY} -bpdz ${BPDZ} -CFL .1 -radius 0.06 -rhoS 2.56 -dlm 1. -ypos .3 -nu 0.000649950425459939 -tdump 1.
#aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./simulation_mordant -file ${SLURM_JOB_NAME} -sim falling -tend 5. -nprocsx ${SLURM_NTASKS} -nprocsy 1 -nprocsz 1 -bpdx 1 -bpdy ${BPDYZ} -bpdz ${BPDYZ} -CFL .1 -radius 0.02 -rhoS 2.56 -dlm 1. -xpos .25 -ypos .2 -zpos .25 -nu 0.000125083017699736 -tdump 0.1
#aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./simulation_mordant -file ${SLURM_JOB_NAME} -sim falling -tend 5. -nprocsx ${SLURM_NTASKS} -nprocsy 1 -nprocsz 1 -bpdx 1 -bpdy ${BPDYZ} -bpdz ${BPDYZ} -CFL .1 -radius 0.02 -rhoS 2.56 -dlm 1. -ypos .5 -nu 0.000646605413200915 -tdump 0.1