#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=2:00:00

#SBATCH --job-name=TestRotations
#SBATCH --account=s436
#SBATCH --partition=viz

export SCR=/scratch/daint/cconti/${SLURM_JOB_NAME}
mkdir -p $SCR

cp ../makefiles/test $SCR/.
cp submit_testRotation $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

BPDYZ=1

export OMP_NUM_THREADS=8
#aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./test -minBPD 1 -maxBPD 8 -test rotation -minDT 1 -maxDT 1 -ic 0 -file testRotation0
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./test -minBPD 1 -maxBPD 32 -test rotation -minDT 1 -maxDT 1 -ic 1 -file testRotation1
