#!/usr/bin/ksh
## submit with sbatch
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=24:00:00
#SBATCH --output=MordantTungsten.%j.o
#SBATCH --error=MordantTungsten.%j.e

#SBATCH --job-name=MordantTungsten_SP_1024_160316
#SBATCH --account=s436
#SBATCH --partition=viz

export SCR=/scratch/daint/cconti/${SLURM_JOB_NAME}
mkdir -p $SCR

cp ../makefiles/simulation_mordant $SCR/.
cp MordantDaint.sh $SCR/.
cp submit_MordantTungsten $SCR/.
cd $SCR

source /opt/modules/default/init/bashexport

MPICH_MAX_THREAD_SAFETY=multiple
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export OMP_WAIT_POLICY=PASSIVE

BPDYZ=32

export OMP_NUM_THREADS=8
aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./simulation_mordant -file ${SLURM_JOB_NAME} -sim falling -tend 10. -nprocsx ${SLURM_NTASKS} -nprocsy 1 -nprocsz 1 -bpdx 1 -bpdy ${BPDYZ} -bpdz ${BPDYZ} -CFL .1 -radius 0.04 -rhoS 14.8 -dlm 1. -ypos .3 -nu 0.000639650960836303 -tdump 1.
#aprun -r 1 -n ${SLURM_NTASKS} -N ${SLURM_NTASKS_PER_NODE} -d 8 ./simulation_mordant -file ${SLURM_JOB_NAME} -sim falling -tend 5. -nprocsx ${SLURM_NTASKS} -nprocsy 1 -nprocsz 1 -bpdx 1 -bpdy ${BPDYZ} -bpdz ${BPDYZ} -CFL .1 -radius 0.08 -rhoS 14.8 -dlm 1. -ypos .3 -nu 0.00180920612799936 -tdump 0.1