/* Compile-time settings. Generated by CMake. */
#ifndef CUBISMUP3D_MACROS_H_GENERATED
#define CUBISMUP3D_MACROS_H_GENERATED

#define CUP_BLOCK_SIZE ${BLOCK_SIZE}

// https://cmake.org/cmake/help/latest/command/configure_file.html
#cmakedefine CUP_ASYNC_DUMP
#cmakedefine CUP_DUMP_SURFACE_BINARY
#cmakedefine CUP_SINGLE_PRECISION
#cmakedefine CUP_HDF5_DOUBLE_PRECISION

#endif
