/* Compile-time settings. Generated by CMake. */
#ifndef CUBISMUP3D_MACROS_H_GENERATED
#define CUBISMUP3D_MACROS_H_GENERATED

// https://cmake.org/cmake/help/latest/command/configure_file.html

#define CUP_ALIGNMENT  64
#define CUP_BLOCK_SIZE ${CUP_BLOCK_SIZE}

// Note: async dump only available if MPI supports multithreading.
#cmakedefine CUP_ASYNC_DUMP
#cmakedefine CUP_DUMP_SURFACE_BINARY
#cmakedefine CUP_HDF5_DOUBLE_PRECISION
#cmakedefine CUP_VERBOSE

#endif
